version: "3"
services:
  mongodb:
    image: mongo
    ports:
        - "27017:27017"
    container_name: bookmark-mongodb
    networks:
      - monitornet
  node:
    image: node:8-alpine
    networks:
      - monitornet
    volumes:
        - ./web:/web
        - /tmp:/tmp
  grafana:
    image: grafana/grafana:5.1.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=adminpass
    ports:
      - "3000:3000"
    container_name: bookmark-grafana
    networks:
      - monitornet
    depends_on:
      - prometheus
      - prometheus-pushgateway
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    container_name: bookmark-prometheus
    networks:
      - monitornet
  prometheus-pushgateway:
    image: prom/pushgateway
    container_name: bookmark-pushgateway
    expose:
      - 9091
    ports:
      - "9091:9091"
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.43.0
#    volumes:
#      - '/:/rootfs:ro'
#      - '/var/run:/var/run:rw'
#      - '/sys:/sys:ro'
#      - '/var/lib/docker/:/var/lib/docker:ro'
#    ports:
#      - "8080:8080"
      
volumes:
  grafana_data:

networks:
  monitornet:
    driver: bridge